<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StrongadminMenuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('strongadmin_menu')->delete();

        \DB::table('strongadmin_menu')->insert(array (
            0 =>
            array (
                'id' => 1,
                'level' => 1,
                'parent_id' => 0,
                'name' => '許可權管理',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 2001,
                'created_at' => '2021-01-06 03:37:40',
                'updated_at' => '2021-05-21 20:10:57',
                'delete_allow' => 2,
            ),
            1 =>
            array (
                'id' => 2,
                'level' => 2,
                'parent_id' => 1,
                'name' => '菜單管理',
                'route_url' => 'strongadmin/adminMenu/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 03:38:18',
                'updated_at' => '2021-09-22 14:47:43',
                'delete_allow' => 2,
            ),
            2 =>
            array (
                'id' => 3,
                'level' => 3,
                'parent_id' => 2,
                'name' => '列表檢視',
                'route_url' => 'strongadmin/adminMenu/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 04:50:41',
                'updated_at' => '2021-09-22 14:47:43',
                'delete_allow' => 2,
            ),
            3 =>
            array (
                'id' => 4,
                'level' => 3,
                'parent_id' => 2,
                'name' => '新增',
                'route_url' => 'strongadmin/adminMenu/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 04:51:07',
                'updated_at' => '2021-09-22 14:47:43',
                'delete_allow' => 2,
            ),
            4 =>
            array (
                'id' => 5,
                'level' => 3,
                'parent_id' => 2,
                'name' => '更新',
                'route_url' => 'strongadmin/adminMenu/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 04:51:24',
                'updated_at' => '2021-09-22 14:47:43',
                'delete_allow' => 2,
            ),
            5 =>
            array (
                'id' => 6,
                'level' => 3,
                'parent_id' => 2,
                'name' => '刪除',
                'route_url' => 'strongadmin/adminMenu/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 04:51:52',
                'updated_at' => '2021-09-22 14:47:43',
                'delete_allow' => 2,
            ),
            6 =>
            array (
                'id' => 7,
                'level' => 1,
                'parent_id' => 0,
                'name' => '產品管理',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 2000,
                'created_at' => '2021-01-06 05:05:27',
                'updated_at' => '2021-05-21 20:08:34',
                'delete_allow' => 1,
            ),
            7 =>
            array (
                'id' => 8,
                'level' => 2,
                'parent_id' => 7,
                'name' => '產品列表',
                'route_url' => 'strongadmin/product/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:06:02',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            8 =>
            array (
                'id' => 10,
                'level' => 3,
                'parent_id' => 8,
                'name' => '檢視',
                'route_url' => 'strongadmin/product/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:07:49',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            9 =>
            array (
                'id' => 11,
                'level' => 3,
                'parent_id' => 8,
                'name' => '新增',
                'route_url' => 'strongadmin/product/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:08:02',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            10 =>
            array (
                'id' => 12,
                'level' => 3,
                'parent_id' => 8,
                'name' => '更新',
                'route_url' => 'strongadmin/product/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:08:18',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            11 =>
            array (
                'id' => 13,
                'level' => 3,
                'parent_id' => 8,
                'name' => '刪除',
                'route_url' => 'strongadmin/product/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:08:37',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            12 =>
            array (
                'id' => 14,
                'level' => 2,
                'parent_id' => 1,
                'name' => '賬號管理',
                'route_url' => 'strongadmin/adminUser/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:21:14',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            13 =>
            array (
                'id' => 15,
                'level' => 3,
                'parent_id' => 14,
                'name' => '檢視',
                'route_url' => 'strongadmin/adminUser/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:22:05',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            14 =>
            array (
                'id' => 16,
                'level' => 3,
                'parent_id' => 14,
                'name' => '更新',
                'route_url' => 'strongadmin/adminUser/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 05:22:45',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            15 =>
            array (
                'id' => 17,
                'level' => 3,
                'parent_id' => 14,
                'name' => '刪除',
                'route_url' => 'strongadmin/adminUser/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:08:39',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            16 =>
            array (
                'id' => 18,
                'level' => 2,
                'parent_id' => 1,
                'name' => '角色管理',
                'route_url' => 'strongadmin/adminRole/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:09:58',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            17 =>
            array (
                'id' => 19,
                'level' => 3,
                'parent_id' => 18,
                'name' => '檢視',
                'route_url' => 'strongadmin/adminRole/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:10:18',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            18 =>
            array (
                'id' => 20,
                'level' => 3,
                'parent_id' => 18,
                'name' => '新增',
                'route_url' => 'strongadmin/adminRole/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:10:30',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            19 =>
            array (
                'id' => 21,
                'level' => 3,
                'parent_id' => 18,
                'name' => '更新',
                'route_url' => 'strongadmin/adminRole/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:10:48',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            20 =>
            array (
                'id' => 22,
                'level' => 3,
                'parent_id' => 18,
                'name' => '刪除',
                'route_url' => 'strongadmin/adminRole/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-06 07:11:02',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            21 =>
            array (
                'id' => 23,
                'level' => 2,
                'parent_id' => 1,
                'name' => '操作日誌',
                'route_url' => 'strongadmin/adminLog/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-07 13:40:48',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 2,
            ),
            22 =>
            array (
                'id' => 24,
                'level' => 3,
                'parent_id' => 23,
                'name' => '刪除',
                'route_url' => 'strongadmin/adminLog/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-07 13:41:44',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 2,
            ),
            23 =>
            array (
                'id' => 25,
                'level' => 3,
                'parent_id' => 23,
                'name' => '檢視',
                'route_url' => 'strongadmin/adminLog/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-08 02:27:07',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 2,
            ),
            24 =>
            array (
                'id' => 26,
                'level' => 3,
                'parent_id' => 18,
                'name' => '分配許可權',
                'route_url' => 'strongadmin/adminRole/assignPermissions',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-08 13:08:33',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            25 =>
            array (
                'id' => 36,
                'level' => 1,
                'parent_id' => 0,
                'name' => '主頁',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 99999,
                'created_at' => '2021-01-08 14:59:46',
                'updated_at' => '2021-01-09 13:58:51',
                'delete_allow' => 2,
            ),
            26 =>
            array (
                'id' => 37,
                'level' => 2,
                'parent_id' => 36,
                'name' => '面板',
                'route_url' => 'strongadmin/index/panel',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-08 16:38:33',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 2,
            ),
            27 =>
            array (
                'id' => 38,
                'level' => 3,
                'parent_id' => 14,
                'name' => '建立',
                'route_url' => 'strongadmin/adminUser/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-13 15:25:40',
                'updated_at' => '2021-09-22 14:47:44',
                'delete_allow' => 1,
            ),
            28 =>
            array (
                'id' => 41,
                'level' => 2,
                'parent_id' => 1,
                'name' => 'Telescope',
                'route_url' => 'strongadmin/telescope/requests',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-19 17:19:57',
                'updated_at' => '2021-09-22 15:32:56',
                'delete_allow' => 1,
            ),
            29 =>
            array (
                'id' => 42,
                'level' => 2,
                'parent_id' => 7,
                'name' => '產品分類',
                'route_url' => 'strongadmin/product/category/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-28 15:29:46',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            30 =>
            array (
                'id' => 43,
                'level' => 3,
                'parent_id' => 42,
                'name' => '檢視',
                'route_url' => 'strongadmin/product/category/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-28 15:30:17',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            31 =>
            array (
                'id' => 44,
                'level' => 3,
                'parent_id' => 42,
                'name' => '建立',
                'route_url' => 'strongadmin/product/category/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-28 15:30:34',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            32 =>
            array (
                'id' => 45,
                'level' => 3,
                'parent_id' => 42,
                'name' => '更新',
                'route_url' => 'strongadmin/product/category/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-28 15:30:53',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            33 =>
            array (
                'id' => 46,
                'level' => 3,
                'parent_id' => 42,
                'name' => '刪除',
                'route_url' => 'strongadmin/product/category/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-01-28 15:31:10',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            34 =>
            array (
                'id' => 47,
                'level' => 1,
                'parent_id' => 0,
                'name' => '文章管理',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 1500,
                'created_at' => '2021-02-22 11:32:46',
                'updated_at' => '2021-05-21 20:09:33',
                'delete_allow' => 1,
            ),
            35 =>
            array (
                'id' => 48,
                'level' => 2,
                'parent_id' => 7,
                'name' => '產品規格',
                'route_url' => 'strongadmin/product/specGroup/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 11:35:43',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            36 =>
            array (
                'id' => 49,
                'level' => 3,
                'parent_id' => 48,
                'name' => '規格組檢視',
                'route_url' => 'strongadmin/product/specGroup/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 12:59:16',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            37 =>
            array (
                'id' => 50,
                'level' => 3,
                'parent_id' => 48,
                'name' => '規格組建立',
                'route_url' => 'strongadmin/product/specGroup/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 12:59:39',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            38 =>
            array (
                'id' => 51,
                'level' => 3,
                'parent_id' => 48,
                'name' => '更新規格組',
                'route_url' => 'strongadmin/product/specGroup/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:00:04',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            39 =>
            array (
                'id' => 52,
                'level' => 3,
                'parent_id' => 48,
                'name' => '刪除規格組',
                'route_url' => 'strongadmin/product/specGroup/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:00:26',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            40 =>
            array (
                'id' => 53,
                'level' => 3,
                'parent_id' => 48,
                'name' => '檢視規格',
                'route_url' => 'strongadmin/product/spec/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:22:51',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            41 =>
            array (
                'id' => 54,
                'level' => 3,
                'parent_id' => 48,
                'name' => '建立規格',
                'route_url' => 'strongadmin/product/spec/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:23:22',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            42 =>
            array (
                'id' => 55,
                'level' => 3,
                'parent_id' => 48,
                'name' => '更新規格',
                'route_url' => 'strongadmin/product/spec/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:23:38',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            43 =>
            array (
                'id' => 56,
                'level' => 3,
                'parent_id' => 48,
                'name' => '刪除規格',
                'route_url' => 'strongadmin/product/spec/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-02-22 13:23:56',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            44 =>
            array (
                'id' => 57,
                'level' => 2,
                'parent_id' => 7,
                'name' => '產品品牌',
                'route_url' => 'strongadmin/product/brand/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-03-15 14:38:53',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            45 =>
            array (
                'id' => 58,
                'level' => 3,
                'parent_id' => 57,
                'name' => '列表檢視',
                'route_url' => 'strongadmin/product/brand/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-03-15 14:39:18',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            46 =>
            array (
                'id' => 59,
                'level' => 3,
                'parent_id' => 57,
                'name' => '建立',
                'route_url' => 'strongadmin/product/brand/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-03-15 14:39:45',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            47 =>
            array (
                'id' => 60,
                'level' => 3,
                'parent_id' => 57,
                'name' => '修改',
                'route_url' => 'strongadmin/product/brand/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-03-15 14:40:02',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            48 =>
            array (
                'id' => 61,
                'level' => 3,
                'parent_id' => 57,
                'name' => '刪除',
                'route_url' => 'strongadmin/product/brand/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-03-15 14:40:50',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            49 =>
            array (
                'id' => 62,
                'level' => 1,
                'parent_id' => 0,
                'name' => '訂單管理',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 1800,
                'created_at' => '2021-05-20 13:54:11',
                'updated_at' => '2021-05-21 20:09:05',
                'delete_allow' => 1,
            ),
            50 =>
            array (
                'id' => 63,
                'level' => 2,
                'parent_id' => 62,
                'name' => '訂單列表',
                'route_url' => 'strongadmin/order/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 13:54:36',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            51 =>
            array (
                'id' => 64,
                'level' => 2,
                'parent_id' => 63,
                'name' => '更新訂單',
                'route_url' => 'strongadmin/order/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 13:54:56',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            52 =>
            array (
                'id' => 65,
                'level' => 2,
                'parent_id' => 63,
                'name' => '刪除訂單',
                'route_url' => 'strongadmin/order/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 13:55:53',
                'updated_at' => '2021-09-22 14:47:45',
                'delete_allow' => 1,
            ),
            53 =>
            array (
                'id' => 66,
                'level' => 2,
                'parent_id' => 63,
                'name' => '取消訂單',
                'route_url' => 'strongadmin/order/cancel',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 13:56:35',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            54 =>
            array (
                'id' => 68,
                'level' => 3,
                'parent_id' => 63,
                'name' => '檢視訂單產品',
                'route_url' => 'strongadmin/order/products',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 14:00:41',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            55 =>
            array (
                'id' => 69,
                'level' => 3,
                'parent_id' => 63,
                'name' => '檢視列表',
                'route_url' => 'strongadmin/order/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 14:02:49',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            56 =>
            array (
                'id' => 72,
                'level' => 1,
                'parent_id' => 0,
                'name' => '會員管理',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 1900,
                'created_at' => '2021-05-20 16:44:51',
                'updated_at' => '2021-05-21 20:08:51',
                'delete_allow' => 1,
            ),
            57 =>
            array (
                'id' => 73,
                'level' => 2,
                'parent_id' => 72,
                'name' => '會員列表',
                'route_url' => 'strongadmin/user/index',
                'status' => 1,
                'sort' => 300,
                'created_at' => '2021-05-20 16:45:23',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            58 =>
            array (
                'id' => 74,
                'level' => 3,
                'parent_id' => 73,
                'name' => '檢視',
                'route_url' => 'strongadmin/user/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 16:45:45',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            59 =>
            array (
                'id' => 75,
                'level' => 3,
                'parent_id' => 73,
                'name' => '更新',
                'route_url' => 'strongadmin/user/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 16:46:01',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            60 =>
            array (
                'id' => 76,
                'level' => 3,
                'parent_id' => 73,
                'name' => '刪除',
                'route_url' => 'strongadmin/user/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-20 16:46:21',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            61 =>
            array (
                'id' => 77,
                'level' => 2,
                'parent_id' => 47,
                'name' => '文章分類',
                'route_url' => 'strongadmin/article/category/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:48:03',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            62 =>
            array (
                'id' => 78,
                'level' => 3,
                'parent_id' => 77,
                'name' => '文章分類檢視',
                'route_url' => 'strongadmin/article/category/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:48:46',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            63 =>
            array (
                'id' => 79,
                'level' => 3,
                'parent_id' => 77,
                'name' => '文章分類建立',
                'route_url' => 'strongadmin/article/category/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:49:51',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            64 =>
            array (
                'id' => 80,
                'level' => 3,
                'parent_id' => 77,
                'name' => '文章分類更新',
                'route_url' => 'strongadmin/article/category/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:50:13',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            65 =>
            array (
                'id' => 81,
                'level' => 3,
                'parent_id' => 77,
                'name' => '文章分類刪除',
                'route_url' => 'strongadmin/article/category/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:50:33',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            66 =>
            array (
                'id' => 82,
                'level' => 2,
                'parent_id' => 47,
                'name' => '文章列表',
                'route_url' => 'strongadmin/article/article/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:53:27',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            67 =>
            array (
                'id' => 83,
                'level' => 3,
                'parent_id' => 82,
                'name' => '檢視文章',
                'route_url' => 'strongadmin/article/article/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:54:00',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            68 =>
            array (
                'id' => 84,
                'level' => 3,
                'parent_id' => 82,
                'name' => '建立文章',
                'route_url' => 'strongadmin/article/article/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:54:19',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            69 =>
            array (
                'id' => 85,
                'level' => 3,
                'parent_id' => 82,
                'name' => '更新文章',
                'route_url' => 'strongadmin/article/article/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:54:32',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            70 =>
            array (
                'id' => 86,
                'level' => 3,
                'parent_id' => 82,
                'name' => '刪除文章',
                'route_url' => 'strongadmin/article/article/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-28 16:54:49',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            71 =>
            array (
                'id' => 87,
                'level' => 2,
                'parent_id' => 72,
                'name' => '意見反饋',
                'route_url' => 'strongadmin/user/feedback/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-29 10:58:33',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            72 =>
            array (
                'id' => 88,
                'level' => 3,
                'parent_id' => 87,
                'name' => '檢視',
                'route_url' => 'strongadmin/user/feedback/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-29 10:58:54',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            73 =>
            array (
                'id' => 89,
                'level' => 3,
                'parent_id' => 87,
                'name' => '回覆',
                'route_url' => 'strongadmin/user/feedback/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-29 10:59:10',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            74 =>
            array (
                'id' => 90,
                'level' => 3,
                'parent_id' => 87,
                'name' => '刪除',
                'route_url' => 'strongadmin/user/feedback/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-05-29 10:59:41',
                'updated_at' => '2021-09-22 14:47:46',
                'delete_allow' => 1,
            ),
            75 =>
            array (
                'id' => 91,
                'level' => 2,
                'parent_id' => 72,
                'name' => '會員等級',
                'route_url' => 'strongadmin/user/userRank/index',
                'status' => 1,
                'sort' => 230,
                'created_at' => '2021-06-01 11:26:43',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            76 =>
            array (
                'id' => 92,
                'level' => 3,
                'parent_id' => 91,
                'name' => '檢視',
                'route_url' => 'strongadmin/user/userRank/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-06-01 11:27:27',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            77 =>
            array (
                'id' => 93,
                'level' => 3,
                'parent_id' => 91,
                'name' => '更新',
                'route_url' => 'strongadmin/user/userRank/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-06-01 11:27:41',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            78 =>
            array (
                'id' => 94,
                'level' => 3,
                'parent_id' => 91,
                'name' => '刪除',
                'route_url' => 'strongadmin/user/userRank/desctroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-06-01 11:28:01',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            79 =>
            array (
                'id' => 95,
                'level' => 3,
                'parent_id' => 91,
                'name' => '建立',
                'route_url' => 'strongadmin/user/userRank/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-06-01 11:28:21',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            80 =>
            array (
                'id' => 103,
                'level' => 1,
                'parent_id' => 0,
                'name' => '網站設定',
                'route_url' => NULL,
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-01 20:43:33',
                'updated_at' => '2021-08-01 20:43:33',
                'delete_allow' => 1,
            ),
            81 =>
            array (
                'id' => 104,
                'level' => 2,
                'parent_id' => 103,
                'name' => '配送方式',
                'route_url' => 'strongadmin/shippingOption/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-01 20:44:13',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            82 =>
            array (
                'id' => 105,
                'level' => 2,
                'parent_id' => 103,
                'name' => '支付方式',
                'route_url' => 'strongadmin/paymentOption/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-02 09:52:12',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            83 =>
            array (
                'id' => 106,
                'level' => 3,
                'parent_id' => 105,
                'name' => '檢視',
                'route_url' => 'strongadmin/paymentOption/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-02 09:52:26',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            84 =>
            array (
                'id' => 107,
                'level' => 3,
                'parent_id' => 105,
                'name' => '新增',
                'route_url' => 'strongadmin/paymentOption/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-02 09:52:40',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            85 =>
            array (
                'id' => 108,
                'level' => 3,
                'parent_id' => 105,
                'name' => '更新',
                'route_url' => 'strongadmin/paymentOption/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-02 09:52:53',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            86 =>
            array (
                'id' => 109,
                'level' => 2,
                'parent_id' => 103,
                'name' => '地區管理',
                'route_url' => 'strongadmin/region/regionCountry/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 10:26:57',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            87 =>
            array (
                'id' => 110,
                'level' => 3,
                'parent_id' => 109,
                'name' => '國家列表',
                'route_url' => 'strongadmin/region/regionCountry/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:06:47',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            88 =>
            array (
                'id' => 111,
                'level' => 3,
                'parent_id' => 109,
                'name' => '國家檢視',
                'route_url' => 'strongadmin/region/regionCountry/show',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:07:29',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            89 =>
            array (
                'id' => 112,
                'level' => 3,
                'parent_id' => 109,
                'name' => '國家更新',
                'route_url' => 'strongadmin/region/regionCountry/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:07:48',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            90 =>
            array (
                'id' => 113,
                'level' => 3,
                'parent_id' => 109,
                'name' => '國家刪除',
                'route_url' => 'strongadmin/region/regionCountry/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:08:08',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            91 =>
            array (
                'id' => 114,
                'level' => 3,
                'parent_id' => 109,
                'name' => '大陸列表',
                'route_url' => 'strongadmin/region/regionContinent/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:08:29',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            92 =>
            array (
                'id' => 115,
                'level' => 3,
                'parent_id' => 109,
                'name' => '大陸更新',
                'route_url' => 'strongadmin/region/regionContinent/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:08:43',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            93 =>
            array (
                'id' => 116,
                'level' => 3,
                'parent_id' => 109,
                'name' => '大陸刪除',
                'route_url' => 'strongadmin/region/regionContinent/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:09:01',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            94 =>
            array (
                'id' => 117,
                'level' => 3,
                'parent_id' => 109,
                'name' => '大陸新增',
                'route_url' => 'strongadmin/region/regionContinent/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-07 11:09:21',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            95 =>
            array (
                'id' => 118,
                'level' => 3,
                'parent_id' => 109,
                'name' => '國家新增',
                'route_url' => 'strongadmin/region/regionCountry/create',
                'status' => 1,
                'sort' => 201,
                'created_at' => '2021-08-07 11:09:38',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            96 =>
            array (
                'id' => 120,
                'level' => 2,
                'parent_id' => 103,
                'name' => '網站設定',
                'route_url' => 'strongadmin/webconfig/show',
                'status' => 1,
                'sort' => 300,
                'created_at' => '2021-08-07 13:06:43',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            97 =>
            array (
                'id' => 121,
                'level' => 3,
                'parent_id' => 63,
                'name' => '關閉訂單',
                'route_url' => 'strongadmin/order/confirm/close',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:56:21',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            98 =>
            array (
                'id' => 122,
                'level' => 3,
                'parent_id' => 63,
                'name' => '確認訂單付款',
                'route_url' => 'strongadmin/order/confirm/paid',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:56:43',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            99 =>
            array (
                'id' => 123,
                'level' => 3,
                'parent_id' => 63,
                'name' => '確認訂單發貨',
                'route_url' => 'strongadmin/order/confirm/shipped',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:56:52',
                'updated_at' => '2021-09-22 14:47:47',
                'delete_allow' => 1,
            ),
            100 =>
            array (
                'id' => 124,
                'level' => 3,
                'parent_id' => 63,
                'name' => '確認訂單退貨',
                'route_url' => 'strongadmin/order/confirm/returned',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:57:05',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            101 =>
            array (
                'id' => 125,
                'level' => 3,
                'parent_id' => 63,
                'name' => '確認訂單完成',
                'route_url' => 'strongadmin/order/confirm/done',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:57:14',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            102 =>
            array (
                'id' => 126,
                'level' => 3,
                'parent_id' => 63,
                'name' => '列印訂單',
                'route_url' => 'strongadmin/order/print',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:57:23',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            103 =>
            array (
                'id' => 127,
                'level' => 3,
                'parent_id' => 63,
                'name' => '訂單詳情',
                'route_url' => 'strongadmin/order/show',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-08 13:57:31',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            104 =>
            array (
                'id' => 128,
                'level' => 3,
                'parent_id' => 120,
                'name' => '儲存網站配置',
                'route_url' => 'strongadmin/webconfig/save/config',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-19 18:16:48',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            105 =>
            array (
                'id' => 129,
                'level' => 3,
                'parent_id' => 120,
                'name' => '設定詳情',
                'route_url' => 'strongadmin/webconfig/show',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-08-19 18:17:49',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            106 =>
            array (
                'id' => 130,
                'level' => 3,
                'parent_id' => 104,
                'name' => '檢視',
                'route_url' => 'strongadmin/shippingOption/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:26:28',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            107 =>
            array (
                'id' => 131,
                'level' => 3,
                'parent_id' => 104,
                'name' => '更新',
                'route_url' => 'strongadmin/shippingOption/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:27:03',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            108 =>
            array (
                'id' => 132,
                'level' => 3,
                'parent_id' => 104,
                'name' => '配送區域列表',
                'route_url' => 'strongadmin/shippingOptionConfig/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:29:55',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            109 =>
            array (
                'id' => 133,
                'level' => 3,
                'parent_id' => 104,
                'name' => '配送區域建立',
                'route_url' => 'strongadmin/shippingOptionConfig/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:30:16',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            110 =>
            array (
                'id' => 134,
                'level' => 3,
                'parent_id' => 104,
                'name' => '配送區域更新',
                'route_url' => 'strongadmin/shippingOptionConfig/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:30:30',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            111 =>
            array (
                'id' => 135,
                'level' => 3,
                'parent_id' => 104,
                'name' => '配送區域刪除',
                'route_url' => 'strongadmin/shippingOptionConfig/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2021-09-07 18:30:47',
                'updated_at' => '2021-09-22 14:47:48',
                'delete_allow' => 1,
            ),
            112 =>
            array (
                'id' => 136,
                'level' => 2,
                'parent_id' => 7,
                'name' => '產品評論',
                'route_url' => 'strongadmin/product/comment/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:39:23',
                'updated_at' => '2022-01-18 16:39:23',
                'delete_allow' => 1,
            ),
            113 =>
            array (
                'id' => 137,
                'level' => 3,
                'parent_id' => 136,
                'name' => '檢視評論列表',
                'route_url' => 'strongadmin/product/comment/index',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:45:25',
                'updated_at' => '2022-01-18 16:45:25',
                'delete_allow' => 1,
            ),
            114 =>
            array (
                'id' => 138,
                'level' => 3,
                'parent_id' => 136,
                'name' => '檢視評論詳情',
                'route_url' => 'strongadmin/product/comment/show',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:45:53',
                'updated_at' => '2022-01-18 16:45:53',
                'delete_allow' => 1,
            ),
            115 =>
            array (
                'id' => 139,
                'level' => 3,
                'parent_id' => 136,
                'name' => '建立評論',
                'route_url' => 'strongadmin/product/comment/create',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:46:18',
                'updated_at' => '2022-01-18 16:46:18',
                'delete_allow' => 1,
            ),
            116 =>
            array (
                'id' => 140,
                'level' => 3,
                'parent_id' => 136,
                'name' => '更新評論',
                'route_url' => 'strongadmin/product/comment/update',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:46:38',
                'updated_at' => '2022-01-18 16:46:38',
                'delete_allow' => 1,
            ),
            117 =>
            array (
                'id' => 141,
                'level' => 3,
                'parent_id' => 136,
                'name' => '刪除評論',
                'route_url' => 'strongadmin/product/comment/destroy',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:46:59',
                'updated_at' => '2022-01-18 16:46:59',
                'delete_allow' => 1,
            ),
            118 =>
            array (
                'id' => 142,
                'level' => 3,
                'parent_id' => 136,
                'name' => '審核通過',
                'route_url' => 'strongadmin/product/comment/approve',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:47:24',
                'updated_at' => '2022-01-18 16:47:24',
                'delete_allow' => 1,
            ),
            119 =>
            array (
                'id' => 143,
                'level' => 3,
                'parent_id' => 136,
                'name' => '審核拒絕',
                'route_url' => 'strongadmin/product/comment/refused',
                'status' => 1,
                'sort' => 200,
                'created_at' => '2022-01-18 16:48:02',
                'updated_at' => '2022-01-18 16:48:02',
                'delete_allow' => 1,
            ),
        ));


    }
}
