<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof \Illuminate\Http\Exceptions\ThrottleRequestsException)
        {
            return response()->json(['code' => 429, 'message' => __('Too Many Attempts.')]);
        }

        if ($e instanceof \Illuminate\Routing\Exceptions\InvalidSignatureException)
        {
            return response()->json(['code' => 428, 'message' => __('Invalid signature. 簽名無效')]);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
